version: '3.8'

services:
  bot:
    build: .
    container_name: tech_support_bot
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: tech_support_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-tech_support}
      - POSTGRES_PORT=${POSTGRES_PORT:-5439}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5439:${POSTGRES_PORT}"
    restart: unless-stopped

volumes:
  postgres_data:
